# Récupérer les données géographiques (pays, villes)

In [1]:
#chargement des modules
import pandas as pd
import datetime
import os
import json
from io import StringIO
import numpy as np
import plotly.express as px
import re

In [2]:
import s3fs #pour connecter au bucket

In [3]:


# Create filesystem object
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})

BUCKET_OUT = "aluneau"

In [4]:
file_path = BUCKET_OUT + "/" + "Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.jsonl"
print(file_path)
list_id_pub = []
datas =[]
with fs.open(file_path, 'r', encoding='utf-8') as file:
    for line in file:
        try:
            data = json.loads(line)
            # Extract specific fields
            ids = data.get('all_ids')
            list_id_pub.append(ids[0])
            datas.append(data)
            
        except json.JSONDecodeError:
            continue  # Skip invalid lines

aluneau/Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.jsonl

La cellule ci-dessous récupèrent les données qui nous intéressent depuis le fichier Json. Ces données seront ensuitre structurées dans un dataframe constitué d'une ligne par publication. 

**Remarque** : Il est probable que les données soient déjà disponibles dans le fichier "bso-publications-latest_199318270_enriched.csv".

In [5]:
authors_halid_s = [] #identifiant HAl au format string : prenom.nom
authors_halid_i = [] # identifiant hal au format numerique, ex: 191919
authors_fullname = [] #nom prénom de l'auteur
authors_orcid = [] #orcid de l'auteur
structures_id = [] #hal id de la structure
structures_country = [] #pays de la structurre (si plusieurs structures, on prend la première dans l'ordre d'apparition)
structures_address = [] #addresse de la structurre (si plusieurs structures, on prend la première dans l'ordre d'apparition)
hal_class_code = [] #Classification hal
bso_class = [] #Classification disciplinaire du BSO
pub_year = [] #Année de publication
pub_date = [] #date de publication
pub_hal_id = [] #hal id de la publication
is_oa = [] #statut d'ouverture en 2024
list_ids = [] #id de la publication dans le fichier du BSO
list_rors = []

for n, x in enumerate(list_id_pub):
    
    dict_pub = datas[n]
    if 'authors' in dict_pub:
        #print(n, x)
        list_author = []
        list_author_id_s = []
        list_author_id_i = []
        list_author_orcid = []
        list_structures_id = []
        list_country = []
        list_address = []
        list_keyword = []
        list_ids.append(x)
        
        for a in dict_pub['authors']:
            #print(a)
            
            if  'full_name' in a:
                list_author.append(a['full_name'])
            else:
                list_author.append('no full_name')
            if 'id_hal_s' in a:
                list_author_id_s.append(a['id_hal_s'])
            else:
                list_author_id_s.append('no_id_hal_s')
            if 'id_hal_i'  in a:
                list_author_id_i.append(a['id_hal_i'])
            else:
                list_author_id_i.append('no_id_hal_i')
            if 'orcid' in a:
                list_author_orcid.append(a['orcid'])
            else:
                list_author_orcid.append('no orcid')
            if "affiliations" in a and len(a["affiliations"]) > 0 :
                dict_affil = a["affiliations"][0]
                if "country" in dict_affil:
                    list_country.append(dict_affil["country"])
                else:
                    list_country.append("no country")
                if "name" in dict_affil:
                    list_address.append(dict_affil["name"])
                else:
                    list_address.append("no address")
            else:
                list_country.append("no country")
                list_address.append("no address")
    
        authors_halid_s.append("|".join(list_author_id_s))
        authors_halid_i.append("|".join(list_author_id_i))
        authors_fullname.append("|".join(list_author))
        authors_orcid.append("|".join(list_author_orcid))
        structures_country.append("|".join(list_country))
        structures_address.append("|".join(list_address))

        if 'hal' in x:
            pub_hal_id.append(x[3:])
        else:
            pub_hal_id.append(np.nan)
        if 'hal_classification' in dict_pub:
            hal_classification = [h['code'] for h in dict_pub['hal_classification']]
            hal_class_code.append('|'.join(hal_classification))
        else:
            hal_class_code.append('no hal_classification')
        bso_class.append(dict_pub['bso_classification'])
        if 'keywords' in dict_pub:
            for kw in dict_pub["keywords"]:
                list_keyword.append(kw["keyword"])
        else:
            list_keyword.append('no keywords')
        affiliations_i = [inst for inst in dict_pub['bso_local_affiliations']  if re.search(r'[a-z]', inst) is None ]
        structures_id.append('|'.join(affiliations_i))
        #pub_date.append(dict_pub['published_date'])
        pub_year.append(dict_pub['year'])
        rors = dict_pub['rors']
        list_rors.append("|".join(rors))

        for y in dict_pub['oa_details']:
            if y == "2024Q4":
                dict_oa = dict_pub['oa_details'][y]
                #published_date.append(dict_pub['external_ids']['published_date'])
                is_oa.append(dict_oa["is_oa"])
    else:
        pass

In [6]:
data_columns = {
    "id": list_ids,
    'hal_id': pub_hal_id,
    "pub_year" : pub_year,
    'authors' : authors_fullname,
    'authhalid_s': authors_halid_s,
    'authhalid_i':authors_halid_i,
    'orcid': authors_orcid,
    'struchal_id': structures_id,
    'struc_country': structures_country,
    'struc_address': structures_address,
    'rors': list_rors,
    'hal_classif' : hal_class_code,
    'bso_classif' : bso_class,
    'is_oa': is_oa
}

df0 = pd.DataFrame(data= data_columns)
df0

,id,hal_id,pub_year,authors,authhalid_s,authhalid_i,orcid,struchal_id,struc_country,struc_address,rors,hal_classif,bso_classif,is_oa
0,halhal-03933378,hal-03933378,2019,Jérôme Livet|François Capron|Philippe Blanchar...,jerome-livet|francois-capron|philippe-blanchar...,176081|15426|18849|245|6836|2483|no_id_hal_i|1...,0000-0002-1785-776X|no orcid|0000-0003-0829-77...,7550|199318270|205557|301475|1059646|11141|178...,France|France|France|France|France|France|Fran...,Institut national de recherches archéologiques...,https://ror.org/04wez5e68|https://ror.org/02ww...,shs.archeo_,Humanities,False
1,halhal-03895949,hal-03895949,2017,Katerina Chryssanthaki-Nagle,no_id_hal_s,no_id_hal_i,no orcid,7550|199318270|11141|300125|1003|441569|105964...,no country,"Archéologies et Sciences de l'Antiquité, UMR70...",https://ror.org/04wez5e68,shs.archeo_|shs.art_|shs.class_|shs.hist_|shs....,Humanities,False
2,halhal-01789653,hal-01789653,2017,Makis Solomos,no_id_hal_s,no_id_hal_i,no orcid,199318270|11141|188359,no country,"Esthétique, musicologie, danse et création mus...",https://ror.org/04wez5e68,shs.musiq_,Humanities,True
3,halhal-03807832,hal-03807832,2014,Isabelle Launay,no_id_hal_s,no_id_hal_i,no orcid,199318270|11141|188359,no country,"Esthétique, musicologie, danse et création mus...",https://ror.org/04wez5e68,shs_|shs.musiq_,Humanities,False
4,doi10.3917/cliop.028.0029,NaN,2022,Léandro de Lajonquière|Floriana Baldassi D’Arrigo,no_id_hal_s|no_id_hal_s,no_id_hal_i|no_id_hal_i,no orcid|no orcid,199318270|199411117|420786|106111|11141,no country|no country,no address|no address,https://ror.org/04wez5e68|https://ror.org/05gg...,shs.edu_|shs.psy_,Social sciences,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48081,halhal-04095338,hal-04095338,2020,Céline Clément,celine-clement-nanterre,1253116,no orcid,439352|441569|199318270|116205|443665|11141,no country,"Genre, Travail, Mobilités, Cresppa-GTM, CRESPP...",https://ror.org/04wez5e68,shs.demo_|shs.socio_,Social sciences,False
48082,halhal-03299923,hal-03299923,2020,Martine Créac'H,martine-creach,746578,no orcid,199318270|1007102|11141,no country,"Fabrique du littéraire, EA7322, Fablitt, UP8, ...",https://ror.org/04wez5e68,shs_|shs.litt_,Humanities,False
48083,halhal-04366816,hal-04366816,2023,Brigitte Bardin|Anne Burguet|Sophie Henry|Nico...,brigitte-bardin|annette-burguet|sophie-henry|n...,1316897|753990|1327258|1268072,no orcid|0009-0005-8979-2706|no orcid|0000-000...,199318270|193113842|217752|1052984|11141|42812...,France|France|France|France,"Laboratoire Parisien de Psychologie Sociale, E...",https://ror.org/04wez5e68|https://ror.org/02v6...,scco.psyc_,Humanities,True
48084,halhal-02120667,hal-02120667,2018,Valentina M. Azzarà|A.P. de Rorre|Jean-Francoi...,no_id_hal_s|no_id_hal_s|jean-francois-berger|g...,no_id_hal_i|no_id_hal_i|742611|13749,no orcid|no orcid|0000-0002-4360-7262|0000-000...,7550|199318270|301232|11141|300311|196901920|1...,France|no country|France|France,"Archéologies et Sciences de l'Antiquité, UMR70...",https://ror.org/04wez5e68|https://ror.org/050j...,shs.archeo_|sde.es_|sdu.stu.gp_,"Earth, Ecology, \nEnergy and applied biology",False
48085,halhal-01964707,hal-01964707,2020,Coralie Vincent,cvincent,4552,no orcid,441569|199318270|204862|475360|11141,no country,"Structures Formelles du Langage, UMR7023, UMR7...",https://ror.org/04wez5e68,spi.signal_|info.info-ts_|shs.musiq_|scco.ling_,Humanities,True

In [7]:
with fs.open(f"{BUCKET_OUT}/Data_bso/outputs/publis/2026-02-18_list_of_publi_from_bso.csv", "w") as file_out:
    df0.to_csv(file_out, sep=",", index= False)

In [ ]:
file_path = BUCKET_OUT + "/" + "Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.csv"
with fs.open(file_path) as csvin:
    df1 = pd.read_csv(csvin, sep =";")

## Retrouver les informations géographiques à partir du ROR

In [8]:
df01 = df0[["id","rors"]]
df01["rors"] = df01.rors.str.split("|")
df_ror = df01.explode("rors")

/tmp/ipykernel_2541/4143035616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df01["rors"] = df01.rors.str.split("|")

In [9]:
import requests
from requests.exceptions import HTTPError
import urllib.parse

In [10]:
ROR_API_ENDPOINT = "https://api.dev.ror.org/organizations"


params = {"query":"1m84wm78"} # le nombre de ligne. Par défaut, l'api affiche les 30 première ligne et le maximum fixé est de 10000.

In [11]:
query_response = requests.get(ROR_API_ENDPOINT + '/' + "01m84wm78").json()

In [12]:
query_response

{'admin': {'created': {'date': '2018-11-14', 'schema_version': '1.0'},
  'last_modified': {'date': '2026-01-29', 'schema_version': '2.1'}},
 'domains': [],
 'established': 1969,
 'external_ids': [{'all': ['grid.11619.3e'],
   'preferred': 'grid.11619.3e',
   'type': 'grid'},
  {'all': ['0000 0001 2152 2279'], 'preferred': None, 'type': 'isni'},
  {'all': ['Q459026'], 'preferred': None, 'type': 'wikidata'}],
 'id': 'https://ror.org/01m84wm78',
 'links': [{'type': 'website', 'value': 'http://www.univ-rennes2.fr/'},
  {'type': 'wikipedia',
   'value': 'http://en.wikipedia.org/wiki/University_of_Rennes_2_%E2%80%93_Upper_Brittany'}],
 'locations': [{'geonames_details': {'continent_code': 'EU',
    'continent_name': 'Europe',
    'country_code': 'FR',
    'country_name': 'France',
    'country_subdivision_code': 'BRE',
    'country_subdivision_name': 'Brittany',
    'lat': 48.11198,
    'lng': -1.67429,
    'name': 'Rennes'},
   'geonames_id': 2983990}],
 'names': [{'lang': 'en',
   'types': ['label'],
   'value': 'University of Rennes 2'},
  {'lang': 'fr',
   'types': ['label', 'ror_display'],
   'value': 'Université Rennes 2'}],
 'relationships': [{'label': 'Laboratoire de Psychologie : Cognition, Comportement, Communication',
   'type': 'child',
   'id': 'https://ror.org/03dgmxj03'},
  {'label': 'Institut de recherche mathématique de Rennes',
   'type': 'child',
   'id': 'https://ror.org/05y76vp22'},
  {'label': 'Laboratoire Mouvement Sport Santé',
   'type': 'child',
   'id': 'https://ror.org/05b3p7p58'},
  {'label': 'Anglophonie: communautés, écritures',
   'type': 'child',
   'id': 'https://ror.org/0595x5h51'},
  {'label': 'Arts: pratiques et poétiques',
   'type': 'child',
   'id': 'https://ror.org/01k9kg969'},
  {'label': 'Arènes: politique, santé publique, environnement, médias',
   'type': 'child',
   'id': 'https://ror.org/00m4rxj18'},
  {'label': 'Centre d’études des langues et littératures anciennes et modernes',
   'type': 'child',
   'id': 'https://ror.org/045q3tp69'},
  {'label': 'Centre d’Etudes des Langues, Territoires et Identités Culturelles – Bretagne et Langues Minoritaires',
   'type': 'child',
   'id': 'https://ror.org/05r4re112'},
  {'label': 'Centre de Recherche en Archéologie, Archéosciences, Histoire',
   'type': 'child',
   'id': 'https://ror.org/02wgtm643'},
  {'label': 'Centre de recherche sur l’éducation, les apprentissages et la didactique',
   'type': 'child',
   'id': 'https://ror.org/00psw8792'},
  {'label': 'Équipe de Recherche Interlangue : Mémoires, Identités, Territoires',
   'type': 'child',
   'id': 'https://ror.org/0339jw085'},
  {'label': 'Espaces et Sociétés',
   'type': 'child',
   'id': 'https://ror.org/03237mt20'},
  {'label': 'Histoire et critique des arts',
   'type': 'child',
   'id': 'https://ror.org/018n13n96'},
  {'label': 'Littoral, Environnement, Télédétection, Géomatique',
   'type': 'child',
   'id': 'https://ror.org/05sat2s07'},
  {'label': 'Linguistique Ingénierie et Didactique des Langues',
   'type': 'child',
   'id': 'https://ror.org/02gn4cf81'},
  {'label': 'Laboratoire Interdisciplinaire de Recherche en Innovations Sociétales',
   'type': 'child',
   'id': 'https://ror.org/01dyfj824'},
  {'label': 'Pôle de Recherche Francophonies, Interculturel, Communication, Sociolinguistique',
   'type': 'child',
   'id': 'https://ror.org/01pxcyx49'},
  {'label': "Pratiques et Théories de l'art contemporain",
   'type': 'child',
   'id': 'https://ror.org/00drkdp66'},
  {'label': 'Recherches en Psychopathologie et Psychanalyse',
   'type': 'child',
   'id': 'https://ror.org/04fke6556'},
  {'label': 'Tempora', 'type': 'child', 'id': 'https://ror.org/05rmjk207'},
  {'label': 'Valeurs, Innovations, Politiques, Socialisations et Sports',
   'type': 'child',
   'id': 'https://ror.org/026m1rk14'},
  {'label': "Observatoire des Sciences de l'Environnement de Rennes",
   'type': 'child',
   'id': 'https://ror.org/05pwkex33'},
  {'label': 'Maison des sciences humaines et sociales en Bretagne',
   'type': 'child',
   'id': 'https://ror.org/01jwwzm25'}],
 'status': 'active',
 'types': ['education']}

In [13]:
for n, x in enumerate(query_response["names"]):
    if 'ror_display' in x["types"]:
        print(x)

{'lang': 'fr', 'types': ['label', 'ror_display'], 'value': 'Université Rennes 2'}

In [14]:
dict_ror = {}
list_row = []
for ror in df_ror.rors.unique():
    dict_row ={}
    rorid = ror.split("/")[-1]
    #print(rorid)
    dict_ror[ror] = rorid
    dict_row["ror"] = ror
    data = requests.get(ROR_API_ENDPOINT + '/' + rorid).json()

    for n, x in enumerate(data["names"]):
        if 'ror_display' in x["types"]:
            dict_row["nom"] = x["value"]
    locations_data = data["locations"][0]["geonames_details"]
    for i in locations_data:
        dict_row[i] = locations_data[i]
        if i == "name":
            dict_row["city"] = locations_data[i]
    dict_row["geonames_id"] = data["locations"][0]["geonames_id"]
    list_row.append(dict_row)

In [15]:
df_inst = pd.DataFrame.from_dict(list_row)

In [16]:
df_inst.country_name.value_counts()

country_name
France    155
Name: count, dtype: int64

## Retrouver le ror à partir du nom des universités

Dans les données enrichies, le ror est présent uniquement pour les établissement français. On va essayer de récupérer le ror à partir de l'adresse des structures (lorsqu'elle est indiquée)

In [26]:
df02 = df0[["id","struc_address"]]
df02["address"] = df02.struc_address.str.split("|")
df_ad = df02.explode("address")
df_ad2 = df_ad.loc[~(df_ad.address.str.contains('no address|France'))]
df_ad2.address.iloc[1]

/tmp/ipykernel_2541/472175067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df02["address"] = df02.struc_address.str.split("|")

'École doctorale Pratiques et théories du sens'

In [39]:
key ='École doctorale Pratiques et théories du sens'
status_response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{key}"').json()
status_response

{'number_of_results': 0,
 'time_taken': 51,
 'items': [],
 'meta': {'types': [], 'countries': [], 'continents': [], 'statuses': []}}

In [55]:
dict_ror2 = {}
for m, a in enumerate(df_ad2.address.unique()):
    row_id = m
    a_split = a.split(",")
    nom_univ = re.sub(r"\[.*\]", "", a_split[0]).strip().replace("&egrave;", "è").lower()
    print(nom_univ)
    #key ='École doctorale Pratiques et théories du sens'
    response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{nom_univ}"').json()
    try:
        if response["number_of_results"] > 1 :
            for n, x in enumerate(response["meta"]["types"]):
                if 'education' in x["id"]:
                    data = response["items"][n]
                    #print(data["id"])
        elif response["number_of_results"] == 1 :
            data = response["items"][0]
            #print(data["id"])
        dict_ror2[row_id] = data["id"]
    except:
        print(nom_univ)

nos últimos trinta anos nos últimos trinta anos
école doctorale pratiques et théories du sens
archeodunum
université de paris viii
université laval
revue des arts et médiations humaines revue des arts et médiations humaines
ecole nationale des sciences appliquées
université de la manouba
université paris 8 : laboratoire d’études et de recherches sur les logiques contemporaines de la philosophie (llcp ea 4008).
école doctorale galilée
the university of tennessee
école doctorale sciences sociales
eberhard karls universität tübingen =  university of tübingen
dans la réforme du travail au mexique dans la réforme du travail au mexique
direction régionale de la pêche de koulikoro
institut français de pondichéry
universidad nacional del centro de la provincia de buenos aires
département d'etude sur l'adaptation scolaire et sociale
iranian center for archaeological research
university professor (exceptional class) at the university of paris university of paris
university of kansas
école doctorale esthétique
exploration and excavation branch
laboratoire de recherche de mécanique
national school of engineers of sfax
graduate school of material science
fundação joão pinheiro
école doctorale abbé grégoire
rheinisch-westfälische technische hochschule aachen university
università degli studi di roma "la sapienza" = sapienza university
institut national d'aménagement et d'urbanisme
unité de modélisation
national school of engineers of sfax
école nationale d'ingénieurs de sfax
national school of engineers of sfax
school of mathematics and statistics
aristotle university of thessaloniki
faculte´ des sciences
institut national de la recherche agronomique
université paris nanterre
nutritional epidemiology research team
equipe de recherche en epidémiologie nutritionnelle
école doctorale espaces
universidade de lisboa = university of lisbon = université de lisbonne
university of strathclyde
école de gestion telfer / université d'ottawa
université m'hamed bougara boumerdes
« blacking up : une histoire du rock au prisme du blacking up : une histoire du rock au prisme
universidad de parís 8
« le forum mondial de l'eau le forum mondial de l'eau
university of paris
yarmouk university
baker university
university of quebec at montreal
university of leicester
city university of hong kong
université evangelique en afrique(uea-bukavu)
culture
seas
robert schuman centre for advanced studies
université hassan ii de casablanca = university of hassan ii casablanca = جامعة الحسن الثاني (ar)
cnrs
université de lausanne = university of lausanne
università di napoli l'orientale = university of naples
université de liège
ministère de la culture et de la communication
universidad de deusto
ufpa
maître de conférences hdr en sociologie
faculty of arts
department of archaeology and ancient near eastern cultures
university of kent
directeur honoraire du musée gréco-romain d'alexandrie
école doctorale cognition
cnrs
alma mater studiorum università di bologna = university of bologna
humboldt-universität zu berlin = humboldt university of berlin = université humboldt de berlin
università degli studi di catania = university of catania
stanford university
institut für mathematik
skane university hospital
ray w. herrick laboratories
érudit est un consortium interuniversitaire sans but lucratif composé de l'université de montréal
italian national research council
université de bâle = university of basel = basel universität
mackenzie presbyterian university
« lumière sur les lumières » ou « contre-lumières » ? relire kritik und krise de reinhart koselleck en contexte lumière sur les lumières » ou « contre-lumières » ? relire kritik und krise de reinhart koselleck en contexte
2 . cnrs
université paris nanterre
dans revue des politiques sociales dans revue des politiques sociales
institut für germanistik
cessp-ehess
northumbria university
university of naples federico ii = università degli studi di napoli federico ii
institut royal des sciences naturelles de belgique = royal belgian institute of natural sciences
maître de conférences en sociologie à l’université blaise-pascal de clermont-ferrand
genome institute of singapore
china agricultural university
centre de recherche francais de jérusalem
kobe university
université paris 8-ler
université paris viii vincennes-saint-denis.
actualité internationale de la littérature
maître de conférences (hdr) – université paris cité – ladyss.
yale university
german aerospace center
max-planck-institut
institut fondamental d'afrique noire
maître de conférences en sociologie à l’université paris-ouest-nanterre-la défense
université paris 1 panthéon-sorbonne
école doctorale d'histoire de l'université paris 1 panthéon-sorbonne
éphorie des antiquités de la phtiotide et de l'evrytanie
institut d'archéologie de l'académie des sciences de l'ouzbékistan [tachkent
institut català de paleoecologia humana i evolució social
centro nacional de investigación sobre la evolución humana
departamento de prehistoria y arqueología
instituto de la comunicación e imagen. universidad de chile las importaciones de literaturas en castellano en francia desde 1945. crecimiento del catálogo literatura de las ediciones seuil y diversidad editorial les instituto de la comunicación e imagen. universidad de chile las importaciones de literaturas en castellano en francia desde 1945. crecimiento del catálogo literatura de las ediciones seuil y diversidad editorial les
université de genève = university of geneva
national council for scientific research = conseil national de la recherche scientifique du liban
* irmar
rautenstrauch-joest museum für völkerkunde
« bouve (catherine bouve (catherine
department of mathematics - university of michigan
bruno menon est maître de conférences à paris 8 où il enseigne dans le master gestion stratégique de l’information. son parcours antérieur inclut un poste de documentaliste à sciences-po puis d’ingénieur r&d dans le secteur du traitement automatique des langues. ses thèmes de recherche
bruno menon est maître de conférences à paris 8 où il enseigne dans le master gestion stratégique de l’information. son parcours antérieur inclut un poste de documentaliste à sciences-po puis d’ingénieur r&d dans le secteur du traitement automatique des langues. ses thèmes de recherche
école nationale d’ingénieurs de monastir
les multiples vies de tigre reale
faculté de l'aménagement
conservatoire botanique de martinique
université des antilles
service archéologique interdépartemental yvelines/hauts-de-seine
università degli studi di ferrara = university of ferrara
university of alaska
1 . f. de singly f. de singly
ministère grec de la culture
computing and mathematical sciences
anthropologue. elle est professeure des universités à l’institut d’études européennes de paris 8 où elle enseigne l’anthropologie urbaine. elle est chercheuse au lavue (laboratoire architecture
darmangeat est enseignant à l'université paris-diderot et chercheur en économie et anthropologie sociale (sophiapol
institut de géographie
anne conchon : université paris 1 panthéon sorbonne
professeur de littérature et media
doctorant contractuel
università degli studi roma tre = roma tre university
professeure émérite de l’institut français de géopolitique-université de paris 8.
universidad nacional de luján
aalborg university
hispanismes revue de la société des hispanistes français hispanismes revue de la société des hispanistes français
laboratoire paragraphe université paris 8 2 rue de la liberté -93526 saint-denis
university of copenhagen = københavns universitet
università degli studi di trento =  university of trento
faculté des lettres et des sciences humaines - université de fribourg
centre d'études mexicaines et centroaméricaines
université libre de bruxelles
université de djibouti
université fan s. noli de korçë
centre de théorie et analyse du droit
cardiff university
university of stirling
presses universitaires de paris sorbonne (pups)
actions h 2020 marie skłodowska curie paris
université paris 8
escola superior de agricultura "luiz de queiroz"
école normale supérieure d’abidjan
department of anthropology
université du québec à montréal = university of québec in montréal
laboratoire archéologie et peuplement de l'afrique (unité d'anthropologie)
university college of london
institut de recherche sur le maghreb contemporain
universitat pompeu fabra
laboratorio di fonetica sperimentale "arturo genre"
université jagellon de cracovie
« queen mother » moore
école doctorale archéologie
ecole d'urbanisme et d'architecture de paysage
école d’urbanisme et d’architecture de paysage
universidad del littoral
universidade de são paulo = university of são paulo
université de rouen-normandie
ecole française de rome
école doctorale sciences pour l'ingénieur
institut supérieur de gestion industrielle de sfax
université de paris 8 vincennes - saint-denis
direction générale des antiquités et des musées de syrie
françois chaubet est professeur d’histoire contemporaine à l’université paris-ouest – nanterre-la défense. spécialiste d’histoire des intellectuels et d’histoire des relations culturelles internationales
est pas un truc de filles ! essai sur le genre en danse est pas un truc de filles ! essai sur le genre en danse
université paris 8
doctorante en géopolitique
center for the study of human origins
institut d'histoire
uwa - uganda wildlife authority
uganda wildlife authority
manchester institute of biotechnology
research laboratory for archaeology and the history of art
department of anthropology
universidad del país vasco
laboratoire lacomofa .université de biskra algérie
lancaster university management school
école doctorale connaissance
institut für phonetik und sprachverarbeitung
michelle franco redondo est post-doctorante au gtm-cresppa centre de recherches sociologiques et politiques de paris et membre du legs (laboratoire d’études de genre et de sexualité). ses recherches portent sur le care
politiques et pratiques de la politiques et pratiques
paris 8 (saint-denis vincennes)
universiteit utrecht / utrecht university
école doctorale histoire moderne et contemporaine
école doctorale droit
géographe
université bordeaux-i
maître de conférence en études germaniques à l'université paris 8 (vincennes / saint-denis) maître de conférence en études germaniques à l'université paris 8 (vincennes / saint-denis
commissaire aux
universidade sorbonne paris nord -paris 13 centro interuniversitário experice universidade sorbonne paris nord paris 13 centro interuniversitário experice
école doctorale arts et médias
mairie de saint denis
universität heidelberg  = heidelberg university
université badji mokhtar
julien netter est maitre de conférences en sciences de l’éducation
الجامعة اللبنانية
section for geogenetics
universidade federal do acre
university of the witwatersrand
direction collaboration et partenariat patient
national cheng kung university
centre de recherches de la grotte scladina
association des professeurs de langues des iut (apliut) http://apliut.revues.org association des professeurs de langues des iut (apliut) http://apliut.revues.org
università degli studi di torino = university of turin
chercheur – université paris viii
centre d'applications et de recherches en telédétection
professeure en sciences de l’information et de la communication
faculty of humanities
st petersburg state university
centre d'études alexandrines
institut français d'archéologie orientale du caire
university of glasgow
laboratoire d'analyse & modélisation des phénomènes aléatoires
laboratoire d'analyse & modélisation des phénomènes aléatoires
helsingin yliopisto = helsingfors universitet = university of helsinki
saudi commission for tourism and heritage
università cattolica del sacro cuore
professeur des universités
trajectoires d’océanie
centre de suivi ecologique
laboratoire de géomatique et d’environnement
l'utilité sociale contre le travail. leçons du travail gratuit et de ses luttes l'utilité sociale contre le travail. leçons du travail gratuit et de ses luttes
institut national de recherche et d'analyse physico-chimique
1 la prévention mondiale de la covid 19: un subalternisme hégémonique des subalternisé.es la prévention mondiale de la covid 19: un subalternisme hégémonique des subalternisé.es
ben-gurion university of the negev
radboud university
institute for language and speech processing
stockholm university
en el mes de diciembre de 1894
institut français du proche-orient
68 des écrivains. crise politique et avant-gardes littéraires paris
supa school of physics and astronomy
departamento de arqueologıa y antropologıa
universidad austral de chile
fundaçao museu do homem americano
universidade federal de pernambuco
the wallace collection
organisation mondiale de la santé - world health organization
ihmc -institut d'histoire moderne et contemporaine (umr 8066) référence électronique ihmc -institut d'histoire moderne et contemporaine ( umr 8066) référence électronique
instituto de geofísica
department of biological sciences
nigerian airspace management agency
laboratoire laque
université de strasbourg
université cadi ayyad
istituto di scienze e tecnologie della cognizione
école doctorale érasme
pontificia universidad católica de chile
anthropologue
centre hospitalier de l'université de montréal
centre d'excellence du partenariat avec les patients et le public
universitat autònoma de barcelona = autonomous university of barcelona = universidad autónoma de barcelona
department of theoretical and applied linguistics
national university of ireland maynooth
université catholique de louvain = catholic university of louvain
université de vienne
département d'electronique
université frères mentouri – constantine 1 = constantine 1 – frères mentouri university
université joseph ki-zerbo
université de bucarest
zeitschrift für alte geschichte zeitschrift für alte geschichte
centre d'études sur les médias
école doctorale de l'école des hautes études en sciences sociales
dipartimento di scienze archeologiche
istituto di geoscienze e georisorse
université paris nanterre
barnard college
politecnico di torino = polytechnic of turin
conservatorio di l'aquila
institut für mathematik
max planck institute for mathematics
department of mathematics
unité modélisation
national school of engineers of sfax
pontifícia universidade católica de são paulo
instituto nacional de bellas artes y literatura
universidad de buenos aires
institut national du patrimoine - tunisie
université de sfax
université de sfax - university of sfax
university of pisa
université sorbonne paris nord
laboratoire de sociologie urbaine
laboratoire de sociologie urbaine
ecole polytechnique fédérale de lausanne
école doctorale education
institut de recherche robert-sauvé en santé et en sécurité du travail
cerro tololo inter-american observatory
caisse nationale d'allocations familiales
« informations sociales caisse nationale d'allocations familiales
« informations sociales
distribution électronique cairn.info pour la découverte. distribution électronique cairn.info pour la découverte la reproduction
école doctorale ville
institut d'archéologie a. guljamov de samarcande
université du québec à trois-rivières
professeur d’histoire médiévale
école doctorale sciences mécaniques et énergétiques
maîtresse de conférences en histoire médiévale
géographe
université de bucarest
des études urbaines comparatistes à une sociologie croisée des politiques urbaines des études urbaines comparatistes à une sociologie croisée des politiques urbaines
polska akademia nauk = polish academy of sciences = académie polonaise des sciences
université de muenster
université de muenster
universidad de valencia
université de bucarest
université paris-8-vincennes-saint-denis
leshan normal university
university of athens
séculos xx séculos xx
centre de recherches en archéologie et patrimoine
gmo unit
ucl - institute of archaeology
university of ottawa
amnis revue de civilisation contemporaine europes/ amériques 15
2016 amnis revue de civilisation contemporaine europes/ amériques 15 2016
centre national de la recherche archéologique (luxembourg)
quelle place pour une industrie automobile en france ? quelle place pour une industrie automobile en france ?
école de communication
ministère grec de la culture
north carolina state university
binghamton university
archeobotanica e paleoecologia
universidad de murcia
interdsciplinay center for archaeology and the evolution of human behaviour
università degli studi di bergamo = university of bergamo
© institut français du proche-orient la question du cursus honorum mamelouk au tournant des xiv e -xv e siècles institut français du proche-orient la question du cursus honorum mamelouk au tournant des xiv e -xv e siècles
recherche de synthèse en sciences humaines association pour la recherche de synthèse en
analyser le jardin collectif urbain en géographie : une lecture du jardinage par les émotions analyser le jardin collectif urbain en géographie : une lecture du jardinage par les émotions
université de grenade
université d'aston
université de valence
rutgers
institutul de lingvistica iorgu iordan bucarest
museo chileno de arte precolombino
laboratoire de recherche en génie logiciel
urbanisation culture société - inrs
université paris i panthéon sorbonne université paris i panthéon sorbonne
maître de conférences en sociologie à l’université paris nanterre et membre de l’idhes (institutions et dynamiques historiques de l’économie et de la société). ses travaux portent sur l’emploi et la protection sociale
graz university of technology
jordan university of science and technology
staffordshire university
netherlands anafylaxis network [dordrecht
department of psychology
université paris 8 vincennes saint-denis / sorbonne université / centre français de recherche en sciences sociales (cefres)
paris 8
università degli studi di milano-bicocca = university of milano-bicocca
afin
strathmore university
jet propulsion laboratory
ar-geo-lab
foundation foz coa
universitat de barcelona
traceolab
department of food science and technology
l'institut français d'etudes anatoliennes
university of ghana
revista de la red interuniversitaria de estudios sobre las literaturas rioplatenses contemporáneas revista de la red interuniversitaria de estudios sobre las literaturas rioplatenses contemporáneas
t-il de l'objection de conscience dans le service civique ? t-il de l'objection de conscience dans le service civique ?
équipe de recherche esthétique des nouveaux médias
centre for urban studies
institute for advanced sustainability studies
université de guyane
laboratoire d’études de genre et de sexualité (legs   umr 8238)
pour nombreux projets créatifs qui l'ont accompagné. merci. je remercie également : mon équipe d'accueil littérature et histoires à paris 8 'incroyable énergie créative et intellectuelle a soufflé le courage dont j'avais besoin non seulement pour cette thèse mais particulier mireille séguy. l'ecole doctorale pratiques et théories le groupe de recherche des doctorant.e.s en genre de paris
uniwersytet im. adama mickiewicza w poznaniu  = adam mickiewicz university in poznań
lomonosov moscow state university = université d'état lomonossov de moscou
the russian academy of sciences [moscow
ater en science politique université paris 8
professeur émérite d’histoire contemporaine à l’université paris 1 panthéon sorbonne (institut d’histoire économique et sociale)
doctorant en sociologie à l’université paris 8 vincennes-saint-denis et au legs (umr 8238).
umr 7041
expérience
université paris 8 vincennes-saint-denis/école pratique des hautes études
beijing jiaotong university
global land ice measurements from space
laboratoire paragraphe
university of wisconsin - milwaukee
peter bürger dans la critique d'art américaine vanguardias y postmodernismo. la recepción de la de peter bürger en la crítica de arte norteamericana avant-gardes et postmodernisme. la réception de la de
universidad de cádiz = university of cádiz
université de mons / university of mons

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [53]:
df0

,id,hal_id,pub_year,authors,authhalid_s,authhalid_i,orcid,struchal_id,struc_country,struc_address,rors,hal_classif,bso_classif,is_oa
0,halhal-03933378,hal-03933378,2019,Jérôme Livet|François Capron|Philippe Blanchar...,jerome-livet|francois-capron|philippe-blanchar...,176081|15426|18849|245|6836|2483|no_id_hal_i|1...,0000-0002-1785-776X|no orcid|0000-0003-0829-77...,7550|199318270|205557|301475|1059646|11141|178...,France|France|France|France|France|France|Fran...,Institut national de recherches archéologiques...,https://ror.org/04wez5e68|https://ror.org/02ww...,shs.archeo_,Humanities,False
1,halhal-03895949,hal-03895949,2017,Katerina Chryssanthaki-Nagle,no_id_hal_s,no_id_hal_i,no orcid,7550|199318270|11141|300125|1003|441569|105964...,no country,"Archéologies et Sciences de l'Antiquité, UMR70...",https://ror.org/04wez5e68,shs.archeo_|shs.art_|shs.class_|shs.hist_|shs....,Humanities,False
2,halhal-01789653,hal-01789653,2017,Makis Solomos,no_id_hal_s,no_id_hal_i,no orcid,199318270|11141|188359,no country,"Esthétique, musicologie, danse et création mus...",https://ror.org/04wez5e68,shs.musiq_,Humanities,True
3,halhal-03807832,hal-03807832,2014,Isabelle Launay,no_id_hal_s,no_id_hal_i,no orcid,199318270|11141|188359,no country,"Esthétique, musicologie, danse et création mus...",https://ror.org/04wez5e68,shs_|shs.musiq_,Humanities,False
4,doi10.3917/cliop.028.0029,NaN,2022,Léandro de Lajonquière|Floriana Baldassi D’Arrigo,no_id_hal_s|no_id_hal_s,no_id_hal_i|no_id_hal_i,no orcid|no orcid,199318270|199411117|420786|106111|11141,no country|no country,no address|no address,https://ror.org/04wez5e68|https://ror.org/05gg...,shs.edu_|shs.psy_,Social sciences,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48081,halhal-04095338,hal-04095338,2020,Céline Clément,celine-clement-nanterre,1253116,no orcid,439352|441569|199318270|116205|443665|11141,no country,"Genre, Travail, Mobilités, Cresppa-GTM, CRESPP...",https://ror.org/04wez5e68,shs.demo_|shs.socio_,Social sciences,False
48082,halhal-03299923,hal-03299923,2020,Martine Créac'H,martine-creach,746578,no orcid,199318270|1007102|11141,no country,"Fabrique du littéraire, EA7322, Fablitt, UP8, ...",https://ror.org/04wez5e68,shs_|shs.litt_,Humanities,False
48083,halhal-04366816,hal-04366816,2023,Brigitte Bardin|Anne Burguet|Sophie Henry|Nico...,brigitte-bardin|annette-burguet|sophie-henry|n...,1316897|753990|1327258|1268072,no orcid|0009-0005-8979-2706|no orcid|0000-000...,199318270|193113842|217752|1052984|11141|42812...,France|France|France|France,"Laboratoire Parisien de Psychologie Sociale, E...",https://ror.org/04wez5e68|https://ror.org/02v6...,scco.psyc_,Humanities,True
48084,halhal-02120667,hal-02120667,2018,Valentina M. Azzarà|A.P. de Rorre|Jean-Francoi...,no_id_hal_s|no_id_hal_s|jean-francois-berger|g...,no_id_hal_i|no_id_hal_i|742611|13749,no orcid|no orcid|0000-0002-4360-7262|0000-000...,7550|199318270|301232|11141|300311|196901920|1...,France|no country|France|France,"Archéologies et Sciences de l'Antiquité, UMR70...",https://ror.org/04wez5e68|https://ror.org/050j...,shs.archeo_|sde.es_|sdu.stu.gp_,"Earth, Ecology, \nEnergy and applied biology",False
48085,halhal-01964707,hal-01964707,2020,Coralie Vincent,cvincent,4552,no orcid,441569|199318270|204862|475360|11141,no country,"Structures Formelles du Langage, UMR7023, UMR7...",https://ror.org/04wez5e68,spi.signal_|info.info-ts_|shs.musiq_|scco.ling_,Humanities,True